### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by 52lemon** [wuyue92tree/django-adminlte-ui#11]
按照文档说明操作，登陆进入列表时报错， windows10 python3.7.5
`
Internal Server Error: /admin/operation/topicvote/
Traceback (most recent call last):
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'change_list_object_tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\lemon\.virtualenvs\FakeV2EX\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 70: 'change_list_object_tools', expected 'endblock'. Did you forget to register or load this tag?
`

**Comment by wuyue92tree** [comment]
你用的django版本是多少
